blogsite/blog/urls.py
from django.urls import path
from .views import postslist, postdetail

urlpatterns = [
    path('', postslist.as_view(), name='post'),
    path('<slug:slug>/', postdetail.as_view(), name='post_detail'),
]




blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blogsite/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish"),
    (2,"Delete")
)

class posts(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    metades = models.CharField(max_length=50, default="new post")
    status = models.IntegerField(choices=STATUS, default=0)
    
    class Meta:
        verbose_name_plural = "Posts"
        ordering = ['-created_on']
        
    def __str__(self):
        return self.title
    

blogsite/blog/views.py
from django.shortcuts import render
from . models import posts
from django.views import generic
from django.views.decorators.http import require_GET
from django.http import HttpResponse
# Create your views here.

class postslist(generic.ListView):
    queryset = posts.objects.filter(status=1).order_by('-created_on')
    template_name = 'home.html'
    paginate_by = 4
    
class postdetail(generic.DetailView):
    model = posts
    template_name = 'post.html'

blogsite/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style>
html, body {
  height: 100%;
}
  body {
    font-family: sans-serif;
    font-size: 18px;
    background-color: #fdfdfd;
display: flex;
  flex-direction: column;
  }
  #nofooter {
flex: 1 0 auto;
}
darkbtn {
color: #66ff99; }
 .dark-mode {
    background-color: black;
    color: white;
  }
  #foot {
    flex-shrink: 0;
    font-family: sans-serif;
background-color: #BDFFD3; color: #00308F;
    bottom: 0px;
    width: 100%;
}
.card-group,.card,.card-footer,.card-body {
border: none;
}
</style>
</head>
<body>
    <div id="bodydiv"><div id="nofooter">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'post' %}">
            <img src="/static/icons/logo.png" width="30" height="30" class="d-inline-block rounded align-top" alt="logo" loading="lazy">
            Platform ICT</a>
            <div class="nav justify-content-end">
                <div class="d-inline"><a class="nav-link text-black font-weight-bold" href="{% url 'post' %}">Posts</a></div>
                </div></div>
        </nav>
        {% block content %}
{% endblock content %}
</div>
<footer class="footer" id="foot">
<div class="container"><h5 style="text-align:center;">Enjoy the Blog and Stay Updated</h5>
<nav class="navbar navbar-expand-lg">
<div class="container-fluid">

    <p>Copyright © Platform ICT Blog</p>
 
 
 
 
 
    <div class="nav justify-content-center" id="navfooter">
    <span><a class="nav-link text-black font-weight-bold" href="#">About</a></span>
    <span><a class="nav-link text-black font-weight-bold" href="#">Privacy</a></span>
    <span><a class="nav-link text-black font-weight-bold" href="#">Terms</a></span>
    <span><a class="nav-link text-black font-weight-bold" href="#">Feed</a></span>
    </div>
    </div>
      </nav>
        </div>
    </footer></div>    
</body>
</html>

blogsite/blog/templates/home.html
{% extends "base.html" %}
{% block metatags %}
<title>Home | Platform Lead ICT</title>
<meta name="description" content="A destination for Learning">
<meta property="og:title" content="Platform Lead ICT">
<meta property="og:site_name" content="Platform Lead ICT">
<meta property="og:url" content="https://Platform Lead ICT.org">
<meta property="og:description" content="A destination for Learning">
<meta property="og:type" content="website">
{% endblock %}
{% block content %}
<style type="text/css">
    body {
       font-family:  'Raleway', sans-serif;}
    .head_text {
        color: white;
    }
.h1, h4 {
font-family: 'Raleway', sans-serif;
}
#mainhome {
text-align: center; }
</style>
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;">
    <div class="container">
      <p class="h1"> Welcome to <strong>Platform ICT Blog</strong></p>
        <p class="h4">A blog about ICT and its applications in the world</p>
    </div>
</header>
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 left">
            {% for post in posts_list %}
            <div class="shadow-none card mb-4" id="newsfeed">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-text text-muted h6"><span>{{ post.author.first_name }} {{ post.author.last_name }}</span> | {{ post.created_on}} </p>

                    <p class="card-text">{{post.metades }}</p>

                    <span><a href="{% url 'post_detail' post.slug  %}" class="btn btn-outline-primary">Read More →</a></span>
                </div>
            </div>
            {% endfor %}
        </div>
</div>
</div>
{% if is_paginated %}
  <nav aria-label="Page navigation container"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li>
 
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

blogsite/blog/templates/post.html
{% extends 'base.html' %}
{% block metatags %}
<title>{{ object.title }}</title>
<meta name="description" content="{{ object.metades}}" />
<meta property="og:title" content="{{ object.title }}">
<meta property="og:url" content="{% url 'post_detail' object.slug %}">
<meta property="og:description" content="{{ object.metades }}">
<meta property="og:type" content="article">
{% endblock %}
{% block content %}
<style type="text/css">
#container img {
border-radius: 29px;
width: 100%;
height: 360px;
opacity: 0.7;
align-content: center;
}
#container img {
opacity: 1.0; }
a {text-align: center; text-decoration: none;}
</style>
<script type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Post",
  "headline": "{{ object.title }}",
  "description": "{{ object.metades }}",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "{% url 'post_detail' object.slug %}"
},
  "author": {
    "@type": "Person",
    "name": "{{ post.author.first_name }} {{ post.author.last_name "
  },
  "publisher": {
    "@type": "Organization",
    "name": "Platform ICT",
  },
  "datePublished": "{{ news.created_on }}",
  "dateModified": "{{ news.created_on }}",
  "mentions": "{{ object.source }}"
}
</script>
<div class="container">
  <div class="row"> 
<div class="col-md-6 left">
        <h1 class="card-title">{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ object.author.first_name }} {{ object.author.last_name }} |{{ object.created_on }}</p>
 
 
 
 
 
        <p class="card-text">{{ object.content | safe }}</p>
 
 
 
 
 
      </div>
       </div>
       </div>
{% endblock content %}